language: cpp
sudo: required
dist: trusty
os: linux
env:
  global:
    - secure: "Ml/5COYd+J36SsZ4TU1FWANPAcL5mUmw1+Jc8iworWh7P8JCXxWB0MADugpBnEThbsr0L11nUH8+4zKevrimirbQsa6JLcpUQ14Npt0cajD/6Ph+ij/cze9+OElN87i3IaCBZ1fY0KAcQ+wlzokoKZcOHa3Agi7/6l3xmujHXLpKTwjYW2iSQwTVKU9a44BeH3onFki5ZPjafaCb3Ln1CEYnCm6BkmOuT+KgvI5ELJ1z12iqucRHFaHYk9/lLLDSqRKXkoYMyQ2MaEYgTZ/9/MQ/tu52ZSCYuwHe6U64VoP8ItQBNnlXHalEtM3+wcDVXoNzYtsHAkk5Y15a66lJU+F/o9sySC5iHy0EEyebNeVXQZHfx0oHYZZHAhvSuzDLjS5MFGN3r/L/qikv98dMqU2OdCARe5sO2WjrsQyLn8dij9PPm9j6vwtXNH8Q5EtPP4fIc0eB8531SRDkyPobs3li50BG91Muc6Q65uZq0h1Xdw971yDwyLwUB/SdXmPlobZwRuR4EzJPbzh2hRFEW14Sx9GNW7slWKre3CemKqL/WDLG/wPlCvcgFlkWESpp/VkNynorpT7xB2O85gJz1fUFTEKjTLjGALXjufdYNOX3beHKHUu0kPZPDSZsQrf4vIPT1uUXkPIbpRgx62KDJfYjCD3ylFdKSWkDKJFU6Bk="
    - GH_REPO_NAME: web-framework
    - DOXYFILE: $TRAVIS_BUILD_DIR/docs/Doxyfile_html
    - GH_REPO_REF: github.com/akrava/web-framework.git
branches:
  only:
    - master
addons:
  coverity_scan:
    project:
      name: "akrava/web-framework"
      description: "web framework c++"
    notification_email: arkadiy@ex.ua
    build_command_prepend: "git clone https://github.com/no1msd/mstch.git; cd mstch; cmake .; make; sudo make install; cd ..; git clone https://github.com/nlohmann/json.git; cd json; cmake .; make; sudo make install; cd ..; cmake .; make"
    build_command: "sudo make install"
    branch_pattern: coverity_scan
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-5
      - g++-5
      - cmake
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz
before_install:
  - echo -n | openssl s_client -connect https://scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
  - sudo ln -s /usr/bin/gcc-5 /usr/local/bin/gcc
  - sudo ln -s /usr/bin/g++-5 /usr/local/bin/g++
  - export CC=/usr/bin/gcc-5
  - export CXX=/usr/bin/g++-5
  - sudo apt-get -qq update
  - sudo apt-get install lcov
  - sudo apt-get install git
  - sudo apt-get install libboost-all-dev
install:
  - wget https://github.com/libcheck/check/releases/download/0.11.0/check-0.11.0.tar.gz
  - tar -xzvf check-0.11.0.tar.gz
  - pushd check-0.11.0 && ./configure --prefix=/usr && make && sudo make install && popd
  - git clone https://github.com/no1msd/mstch.git
  - cd mstch
  - cmake .
  - make
  - sudo make install
  - cd ..
  - git clone https://github.com/nlohmann/json.git
  - cd json
  - cmake .
  - make
  - sudo make install
  - cd ..
before_script:
  - cmake .
script:
  - make
  - sudo make install
after_success:
  - cd $TRAVIS_BUILD_DIR
  - chmod +x ./docs/generate_documentation.sh
  - ./docs/generate_documentation.sh